# Generated by Django 5.2 on 2025-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='fallback_thumbnail.png', upload_to=''),
        ),
    ]
